# This is a basic workflow that is manually triggered

name: Compile Handler

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: 
    - master

  pull_request:
    branches:
    - master
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2.7.0
      
    - name: Compile xpc_set_event_stream_handler
      run: swift build -v --configuration release --package-path XPCEventStreamHandler
    
    - name: Upload Compiled Handler
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: handle-xpc-event-stream # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: XPCEventStreamHandler/.build/release/handle-xpc-event-stream
        # The desired behavior if no files are found using the provided path.
